name: Podcast-to-Reels CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Run tests with coverage
      run: |
        pytest --cov=podcast_to_reels tests/
    
    - name: Check coverage threshold
      run: |
        pytest --cov=podcast_to_reels --cov-report=term-missing --cov-fail-under=80 tests/
    
    - name: Run sample pipeline (truncated)
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
      run: |
        # Run with a very short duration for CI purposes
        python scripts/run_pipeline.py --url https://youtu.be/dQw4w9WgXcQ --duration 10 --output output/ci_test.mp4 || echo "Pipeline test skipped due to missing API keys"
